name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify Java Version
        run: |
          java -version
          javac -version
          mvn -version

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Maven Settings
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mkdir -p ~/.m2

          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

          echo "===== Maven Settings ====="
          cat ~/.m2/settings.xml

      - name: Test Nexus Authentication
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
            http://54.206.127.76:8081/repository/maven-snapshots/

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd app
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=novapay \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.token="$SONAR_TOKEN"

      - name: Build and Publish JAR to Nexus
        run: |
          cd app
          mvn clean deploy

      - name: Build Docker Image
        run: |
          docker build --no-cache -t alokdocker8700/novapay-app:${{ github.sha }} ./app

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'alokdocker8700/novapay-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image
        run: |
          docker push alokdocker8700/novapay-app:${{ github.sha }}

      - name: Update Helm values.yaml
        run: |
          sed -i 's/tag:.*/tag: "${{ github.sha }}"/' novapay-chart/values.yaml

      - name: Commit Updated Helm Chart
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add novapay-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"

          git push

      - name: Package Helm Chart
        run: |
          helm package novapay-chart

      - name: Upload Helm Chart to Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
            --upload-file novapay-chart-0.1.0.tgz \
            ${{ secrets.NEXUS_HELM_REPO }}
